version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing security scanning utilities...
      - pip install checkov
  build:
    commands:
      - echo Scanning Terraform files...
      - checkov -d . --framework terraform